name: A-share Timing Bot

on:
  schedule:
    - cron: "0 13 * * 1-5"     # 工作日 21:00 (UTC+8)
    - cron: "*/10 * * * *"     # 轮询 /status
  workflow_dispatch:
    inputs:
      mode:
        description: "run/status/poll"
        required: false
        default: "status"
      debug:
        description: "Set DEBUG=1 for verbose logs"
        required: false
        default: "0"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Decide mode (scheduled or poll)
        id: decide
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            H=$(date -u +%H); M=$(date -u +%M); DOW=$(date -u +%u)
            if [ "$H" = "13" ] && [ "$M" = "00" ] && [ $DOW -ge 1 ] && [ $DOW -le 5 ]; then
              echo "mode=run" >> $GITHUB_OUTPUT
            else
              echo "mode=poll" >> $GITHUB_OUTPUT
            fi
          else
            echo "mode=${{ inputs.mode }}" >> $GITHUB_OUTPUT
          fi

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
          TE_API_KEY: ${{ secrets.TE_API_KEY }}
          DEBUG: ${{ inputs.debug }}
        run: |
          echo "Mode: ${{ steps.decide.outputs.mode }}, DEBUG=${DEBUG}"
          if [ "${{ steps.decide.outputs.mode }}" = "run" ]; then
            python bot.py run
          elif [ "${{ steps.decide.outputs.mode }}" = "status" ]; then
            python bot.py status
          else
            python bot.py poll 9
          fi
